name: Build

on:
  # push:
  #   branches:
  #     - main
  #     - 'release/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  LC_ALL: "en_US.UTF-8"
  CONAN_REVISIONS_ENABLED: "1"
  CONAN_NON_INTERACTIVE: "1"
  CONAN_REF: fep_oss/testing
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    strategy:
      matrix:
        name:
          [
            "ubuntu20",
            "windows2019",
          ]
        include:
          - name: "ubuntu20"
            os: ubuntu-20.04
            profile: linux_gcc_9_relwithdebinfo
          - name: "windows2019"
            os: windows-2019
            profile: win_142_relwithdebinfo

    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies for testing in Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |  # terminal, file manager, xwininfo, text-editor
          sudo apt install g++-10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          # cache: 'pip' # caching pip dependencies
      - name: Install specific Conan version
        run: | # markupsafe is a workaround fix for broken conan dependencies
          pip install "conan==1.59.0" --use-pep517
      - name: Add remote
        run: |
            conan remote add fep3_oss ${{ vars.FEP3_GITLAB_URL }} false
      - name: Log in to remote
        run: |
            conan user -p ${{ secrets.GITLAB_FEP3_PW }} -r fep3_oss ${{ secrets.GITLAB_FEP3_USERNAME }}W
      - name: Build own package
        run: |
            conan create . ${{ env.CONAN_REF }} -pr build_profiles/${{ matrix.profile}}
      - name: Upload conan package
        run: |
            conan upload fep3_fast_dds_plugin* -r=fep3_oss --force --all -c

  build_armv8_docker:
    runs-on: ubuntu-latest
    env:
      CONAN_PR_ARG: "-pr build_profiles/linux_armv8_gcc9_relwithdebinfo"
    steps:
      # this checks out repo and it will be the cwd in the docker container automatically in substep run
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          install: | 
            apt-get update -q -y
            apt-get install git g++-9 gcc-9 python3 python3-pip -y
            pip install "conan==1.59.0" --use-pep517
          run: |
            uname -a
            ls -a
            git config --global --add safe.directory /home/runner/work/fep3_fast_dds_plugin/fep3_fast_dds_plugin
            git status
            conan remote clean
            conan remote add fep3_oss ${{ vars.FEP3_GITLAB_URL }} false
            conan user -p ${{ secrets.GITLAB_FEP3_PW }} -r fep3_oss ${{ secrets.GITLAB_FEP3_USERNAME }}
            conan remote add conancenter https://center.conan.io false
            export PATH=$PATH:$PWD/bin && conan create conanfile.py ${{ env.CONAN_REF }} ${{ env.CONAN_PR_ARG }}
            conan upload "fep3_fast_dds_plugin*" -r=fep3_oss --all --confirm --force
            conan remove "fep3_fast_dds_plugin*" -r=fep3_oss --force --outdated 